import React, { useEffect, useRef, useState } from 'react';
import { ArrowUp, ArrowDown, ScanLine, Check, LockKeyhole, Pin, Microscope, AlignHorizontalJustifyStart } from 'lucide-react';
import RangeControl from '../RangeControl';
import { SoundFX } from '../SoundFX';
import PuzzleFrame from './PuzzleFrame';
import { circuitReading, trapReading, comparisonScore } from '../../../../shared/lab-model.js';
const fmt = n => Number(n).toFixed(2).replace('.', ',');
const time = minute => `21:${String(minute).padStart(2, '0')}`;
const Frame = PuzzleFrame;
function Readout({ label, value, unit, tone }) { return <div className={`lab-readout ${tone || ''}`}><span>{label}</span><strong className="font-mono">{value}<small>{unit}</small></strong></div>; }
function Rule({ children }) { return <div className="instrument-rule">{children}</div>; }
export function CircuitPuzzle({ challenge: ch, ...props }) {
  const [proof, setProof] = useState({ rotations: ch.tiles.map(t => t.rotation), voltage: ch.voltage });
  const reading = circuitReading(ch, proof);
  const rotate = i => {
    const rotations = [...proof.rotations]; rotations[i] = (rotations[i] + 1) % 4;
    const next = { ...proof, rotations }; setProof(next);
    const nextReading = circuitReading(ch, next);
    if (nextReading.connected && !nextReading.fault && !reading.connected) SoundFX.playConnect(); else SoundFX.playRotate();
  };
  const safe = reading.current >= ch.currentBand[0] && reading.current <= ch.currentBand[1];
  const visual = <><div className="scene-label"><span>Проводники и выход нагрузки</span><span className="scene-status">{reading.fault ? 'Повреждённая ветвь' : reading.connected ? 'Контур замкнут' : 'Контур разомкнут'}</span></div>
    <div className="circuit-board" style={{ '--board-cols': ch.cols }}>{ch.tiles.map((tile, i) => <button key={tile.id} type="button" className={`circuit-node ${reading.powered.includes(i) ? 'is-powered' : ''} ${tile.damaged ? 'is-damaged' : ''}`} disabled={tile.fixed} aria-label={`${tile.label}${tile.damaged ? ', повреждённый' : ''}, угол ${proof.rotations[i] * 90}°. Повернуть`} onClick={() => rotate(i)}>
      <svg viewBox="0 0 100 100" aria-hidden="true"><g transform={`rotate(${proof.rotations[i] * 90} 50 50)`}>{tile.ports.map(port => { const p = [[50,0],[100,50],[50,100],[0,50]][port]; return <path key={port} d={`M50 50 L${p[0]} ${p[1]}`} fill="none" stroke="currentColor" strokeWidth="8" strokeLinecap="round" />; })}</g><circle cx="50" cy="50" r="9" fill="var(--lab-panel)" stroke="currentColor" strokeWidth="3" />{tile.damaged && <path d="M38 38L62 62M62 38L38 62" stroke="var(--lab-warning)" strokeWidth="4" />}</svg>
      <span>{i === 0 ? 'IN' : i === ch.tiles.length - 1 ? 'OUT' : i + 1}</span><small>{tile.fixed ? '•' : `${proof.rotations[i] * 90}°`}</small>
    </button>)}</div><p className="scene-caption">Нажатие поворачивает узел на 90°. IN — источник, OUT — выход. Соедините соседние порты; пунктир и крест обозначают повреждённые узлы.</p></>;
  const controls = <><Readout label="Ток на выходе" value={fmt(reading.current)} unit="А" tone={safe ? 'readout-safe' : ''} /><Rule><strong>Паспорт нагрузки</strong><p>Сопротивление: {ch.resistance} Ω.<br />Рабочий ток: {ch.currentBand.join('–')} А.<br />Расчёт: I = U / R.</p>{ch.stage > 0 && <p>Повреждённый предохранитель не должен попадать в запитанную ветвь.</p>}</Rule><RangeControl label="Напряжение источника" value={proof.voltage} min={ch.voltageMin} max={ch.voltageMax} step={ch.voltageStep} unit="В" onChange={voltage => setProof({ ...proof, voltage })} /><div className="meter-track" role="img" aria-label={`Ток ${fmt(reading.current)} А; диапазон ${ch.currentBand.join('–')}`}><span style={{ width: `${Math.min(100, reading.current / 4.5 * 100)}%` }} /></div></>;
  return <Frame {...props} proof={proof} visual={visual} controls={controls} instruction="Восстановите путь до выхода, затем подберите ток по паспорту нагрузки. Вращайте только подвижные узлы." hint="Начните с источника и проследите каждый стык. После замыкания подберите напряжение по формуле, а не по яркости подсветки." />;
}
function Spectrum({ sample, offset, band, scanned }) {
  const width = 360, height = 170, peak = (sample?.peak || 414) - offset;
  const x = value => 18 + (value - 380) / 90 * 324;
  const points = Array.from({ length: 91 }, (_, i) => { const value = 380 + i; const amplitude = Math.exp(-((value - peak) ** 2) / 45) * 110 + Math.exp(-((value - (peak + 24)) ** 2) / 28) * 15; return `${x(value)},${145 - amplitude}`; });
  return <svg viewBox={`0 0 ${width} ${height}`} className="spectrum-chart" role="img" aria-label={scanned ? `Спектр: пик ${peak} нм, отношение ${sample.ratio}` : 'Спектр появится после сканирования'}><rect x={x(band[0])} y="12" width={x(band[1])-x(band[0])} height="133" fill="var(--lab-cyan)" opacity=".08" />{[380,405,425,450,470].map(t => <g key={t}><line x1={x(t)} x2={x(t)} y1="12" y2="145" stroke="var(--lab-line)" /><text x={x(t)} y="163" textAnchor="middle" fill="var(--lab-muted)" fontSize="11">{t}</text></g>)}{scanned ? <polyline points={points.join(' ')} fill="none" stroke="var(--lab-cyan)" strokeWidth="2.5" /> : <text x="180" y="82" fill="var(--lab-muted)" textAnchor="middle" fontSize="14">Нет измерения</text>}</svg>;
}
export function SpectralPuzzle({ challenge: ch, ...props }) {
  const [selected, setSelected] = useState(ch.samples[0].id), [prepared, setPrepared] = useState([]), [scanned, setScanned] = useState([]), [lamp, setLamp] = useState(false), [scanning, setScanning] = useState(false);
  const [proof, setProof] = useState({ zeroOffset: 0, sampleIds: [] });
  const timer = useRef(null); useEffect(() => () => clearTimeout(timer.current), []);
  const sample = ch.samples.find(s => s.id === selected), measured = scanned.includes(selected);
  const scan = () => { if (!lamp || !prepared.includes(selected)) return; setScanning(true); SoundFX.playScan(); const id = selected; timer.current = setTimeout(() => { setScanned(old => [...new Set([...old, id])]); setScanning(false); }, 580); };
  const visual = <><div className="scene-label"><span>Спектральный профиль</span><span>{scanning ? 'Сканирование…' : lamp ? 'УФ-лампа включена' : 'УФ-лампа выключена'}</span></div><Spectrum sample={sample} offset={proof.zeroOffset} band={ch.band} scanned={measured} /><div className="spectrum-values"><Readout label="Пик с поправкой" value={measured ? sample.peak - proof.zeroOffset : '—'} unit="нм" /><Readout label="Отношение сигналов" value={measured ? sample.ratio.toFixed(1) : '—'} /></div><p className="sample-observation" role="status">{measured ? `Реакция образца «${sample.label}»: ${sample.reaction === 'positive' ? 'положительная' : 'отрицательная'}.` : 'Обработайте выбранный образец и выполните сканирование.'}</p><div className="sample-list">{ch.samples.map(s => <div key={s.id} className={`sample-row ${selected === s.id ? 'sample-active' : ''}`}><button type="button" aria-pressed={selected === s.id} onClick={() => { setSelected(s.id); SoundFX.playClick(); }}><span>{s.label}</span><small>{scanned.includes(s.id) ? 'Измерение готово' : 'Не исследован'}</small></button><label><input type="checkbox" disabled={!scanned.includes(s.id)} checked={proof.sampleIds.includes(s.id)} onChange={e => { setProof({ ...proof, sampleIds: e.target.checked ? [...proof.sampleIds, s.id] : proof.sampleIds.filter(id => id !== s.id) }); SoundFX.playLetterSelect(); }} />В вывод</label></div>)}</div></>;
  const controls = <><Rule><strong>Критерии отбора</strong><p>Положительная реакция, пик {ch.band.join('–')} нм{ch.stage === 2 ? ` и отношение сигналов ≥ ${ch.minRatio}` : ''}. Отметьте все подходящие образцы.</p><p>Контрольная линия: {ch.calibration.expected} нм.<br />Прибор показывает: {ch.calibration.observed} нм.</p></Rule>{ch.stage > 0 && <RangeControl label="Смещение нуля прибора" value={proof.zeroOffset} min={-10} max={10} unit="нм" onChange={zeroOffset => setProof({ ...proof, zeroOffset })} />}<button type="button" className="lab-secondary" disabled={prepared.includes(selected)} onClick={() => { setPrepared([...prepared, selected]); SoundFX.playLatch(); }}>{prepared.includes(selected) ? <Check size={18} /> : <ScanLine size={18} />}{prepared.includes(selected) ? 'Реагент нанесён' : 'Нанести реагент'}</button><button type="button" className="lab-secondary" aria-pressed={lamp} onClick={() => { setLamp(!lamp); SoundFX.playClick(); }}>{lamp ? 'Выключить УФ-лампу' : 'Включить УФ-лампу'}</button><button type="button" className="lab-secondary" disabled={!lamp || !prepared.includes(selected) || scanning} onClick={scan}><ScanLine size={18} />{scanning ? 'Сканирование…' : 'Сканировать образец'}</button><p className="control-note">После измерения добавьте образец в вывод, если он соответствует всем критериям.</p></>;
  return <Frame {...props} proof={proof} visual={visual} controls={controls} instruction="Исследуйте образцы по очереди: реагент → УФ-лампа → сканирование. Одного свечения недостаточно для заключения." hint="Смещение нуля — показание контрольной линии минус её паспортное значение. Вычтите смещение из измеренных пиков; отрицательный контроль не должен попасть в вывод." />;
}
export function TimelinePuzzle({ challenge: ch, ...props }) {
  const [proof, setProof] = useState({ order: ch.events.map(e => e.id), clockCorrection: 0 }); const moved = useRef(null);
  useEffect(() => { const el = moved.current; if (el?.isConnected) (el.disabled ? el.parentElement.querySelector('button:not(:disabled)') : el)?.focus(); }, [proof.order]);
  const move = (index, direction, control) => { moved.current = control; const order = [...proof.order]; [order[index], order[index + direction]] = [order[index + direction], order[index]]; setProof({ ...proof, order }); SoundFX.playRotate(); };
  const [announcement, setAnnouncement] = useState('');
  const visual = <><div className="scene-label"><span>Причинная лента</span><span>{ch.events.length} событий</span></div><ol className="causal-list">{proof.order.map((id, i) => { const e = ch.events.find(x => x.id === id), minute = e.observedMinute + (e.source === 'Терминал' ? proof.clockCorrection : 0); return <li key={id}><span className="event-time font-mono">{time(minute)}</span><div className="event-copy"><strong>{e.title}</strong><span>{e.source}</span><p>{e.note}</p></div><div className="event-move"><button type="button" disabled={i === 0} aria-label={`Выше: ${e.title}`} onClick={event => { move(i, -1, event.currentTarget); setAnnouncement(`${e.title}: позиция ${i} из ${proof.order.length}.`); }}><ArrowUp size={18} /></button><button type="button" disabled={i === proof.order.length - 1} aria-label={`Ниже: ${e.title}`} onClick={event => { move(i, 1, event.currentTarget); setAnnouncement(`${e.title}: позиция ${i + 2} из ${proof.order.length}.`); }}><ArrowDown size={18} /></button></div></li>; })}</ol><span className="sr-only" role="status">{announcement}</span></>;
  const controls = <><Rule><strong>Связи в протоколе</strong><ul>{ch.constraints.map(rule => <li key={rule}>{rule}</li>)}</ul></Rule>{ch.sync && <><Rule><strong>Контроль синхронизации</strong><p>Терминал: {time(ch.sync.observed)}.<br />Эталон: {time(ch.sync.reference)}.</p><p>Поправка прибавляется только к времени терминала.</p></Rule><RangeControl label="Поправка журнала" value={proof.clockCorrection} min={-5} max={5} unit="мин" onChange={clockCorrection => setProof({ ...proof, clockCorrection })} /></>}<p className="control-note">Перемещайте события стрелками. Проверка не отмечает «правильную ячейку» заранее.</p></>;
  return <Frame {...props} proof={proof} visual={visual} controls={controls} instruction="Соберите причинную цепочку по протоколу. На последнем этапе сначала согласуйте часы разных источников." hint="Отделите показание часов от порядка событий. Детали должны существовать до сборки, а уборка не может предшествовать действиям, следы которых она устраняет." submitLabel="Проверить причинную цепь" />;
}
export function TrapPuzzle({ challenge: ch, ...props }) {
  const [proof, setProof] = useState({ release: 50, opening: 0, damper: 0, pinReleased: false, primingRelease: null });
  const force = trapReading(ch, proof), safe = force >= ch.safeBand[0] && force <= ch.safeBand[1];
  const canPrime = proof.opening === 0 && proof.damper === 0 && ch.baseLoad - proof.release >= ch.safeBand[0] && ch.baseLoad - proof.release <= ch.safeBand[1];
  const visual = <><div className="scene-label"><span>Реконструкция спускового механизма</span><span>{proof.pinReleased ? 'Штифт извлечён' : 'Предохранитель на месте'}</span></div><svg className="trap-diagram" viewBox="0 0 420 270" role="img" aria-label={`Капкан: раскрытие ${proof.opening} мм, усилие ${fmt(force)} Н, ${proof.pinReleased ? 'штифт извлечён' : 'штифт на месте'}`}><path d="M50 230H370" stroke="var(--lab-line)" strokeWidth="3" /><ellipse cx="210" cy="212" rx="104" ry="25" fill="var(--lab-panel)" stroke="var(--lab-muted)" /><circle cx="210" cy="200" r="26" fill="var(--lab-panel)" stroke="var(--lab-pink)" strokeWidth="3" /><g style={{ transformOrigin: '106px 200px', transform: `rotate(${-proof.opening}deg)` }}><path d="M106 200C112 98 166 76 210 72" fill="none" stroke="var(--lab-cyan)" strokeWidth="8" />{[130,155,180].map((x,i) => <path key={x} d={`M${x} ${130-i*20}l10 12`} stroke="var(--lab-cyan)" strokeWidth="4" />)}</g><g style={{ transformOrigin: '314px 200px', transform: `rotate(${proof.opening}deg)` }}><path d="M314 200C308 98 254 76 210 72" fill="none" stroke="var(--lab-cyan)" strokeWidth="8" /></g><path d="M62 191q12 -16 24 0t24 0t24 0" fill="none" stroke={safe ? 'var(--lab-success)' : 'var(--lab-warning)'} strokeWidth="4" />{!proof.pinReleased && <path d="M197 198H245" stroke="var(--lab-warning)" strokeWidth="7" />}<text x="210" y="252" textAnchor="middle" fill="var(--lab-muted)" fontSize="14">Условная модель нагрузки</text></svg><Readout label="Усилие пружины" value={fmt(force)} unit="Н" tone={safe ? 'readout-safe' : ''} /><div className="force-gauge"><span style={{ left: `${Math.max(0, Math.min(100, force / 150 * 100))}%` }} /></div><p className="scene-caption">Безопасное окно: {ch.safeBand.join('–')} Н. {ch.stage > 0 ? `Раскрытие должно быть ${ch.openingBand.join('–')} мм.` : 'Сначала научитесь разгружать пружину.'}</p></>;
  const controls = <><Rule><strong>Баланс нагрузки</strong><p>Исходное усилие: {ch.baseLoad} Н.<br />Усилие = {ch.baseLoad} − разгрузка{ch.stage > 0 ? ` + ${ch.leverage} × раскрытие` : ''}{ch.stage === 2 ? ` − ${ch.damping} × демпфер` : ''}.</p></Rule><RangeControl label="Разгрузка пружины" value={proof.release} min={0} max={100} unit="Н" onChange={release => setProof({ ...proof, release })} />{ch.stage > 0 && <><button type="button" className="lab-secondary" disabled={!canPrime && !proof.pinReleased} onClick={() => { if (proof.pinReleased) setProof({ ...proof, opening: 0, damper: 0, pinReleased: false, primingRelease: null }); else { setProof({ ...proof, pinReleased: true, primingRelease: proof.release }); SoundFX.playLatch(); } }}>{proof.pinReleased ? <Pin size={18} /> : <LockKeyhole size={18} />}{proof.pinReleased ? 'Вернуть предохранитель' : 'Извлечь штифт'}</button><RangeControl disabled={!proof.pinReleased} label="Раскрытие механизма" value={proof.opening} min={0} max={40} unit="мм" onChange={opening => setProof({ ...proof, opening })} />{ch.stage === 2 && <RangeControl disabled={!proof.pinReleased} label="Демпфер" value={proof.damper} min={0} max={ch.maxDamper} unit="Н" onChange={damper => setProof({ ...proof, damper })} />}<p className="control-note">Штифт извлекается только при безопасном усилии, нулевом раскрытии и нулевом демпфере.</p></>}</>;
  return <Frame {...props} proof={proof} visual={visual} controls={controls} instruction="Разгрузите пружину. На следующих этапах освободите предохранитель и удержите безопасное усилие при раскрытии." hint="Настройте разгрузку при закрытых губках, извлеките штифт, затем компенсируйте рост усилия при раскрытии. На третьем этапе для компенсации появляется демпфер." />;
}
function RidgeView({ ridges, rotation = 0, offset = 0, focus = 100, reference, overlay }) {
  const lines = (values, angle, shift, color, opacity = 1) => <g transform={`translate(100 90) rotate(${angle}) translate(${-100 + shift} -90)`} opacity={opacity}><path d="M28 139L40 40L167 29L174 139Z" fill="none" stroke={color} strokeWidth="2" />{values.map((x,i) => <path key={`${x}-${i}`} d={`M${38 + x} ${39 - x*.07}l${i % 2 ? 3 : -2} ${45 + (i%3)*13}`} fill="none" stroke={color} strokeWidth={i%2 ? 1.5 : 2.5} />)}</g>;
  return <svg className="ridge-view" viewBox="0 0 200 170" role="img" aria-label={`Борозды ${ridges.join(', ')}, поворот ${rotation}°, смещение ${offset}`}><g style={{ filter: `blur(${Math.max(0, (100-focus)/32)}px)` }}>{lines(ridges, rotation, offset, 'var(--lab-cyan)')}{overlay && reference && lines(reference.ridges, reference.rotation, reference.offset, 'var(--lab-text)', .45)}</g><path d="M12 150H188" stroke="var(--lab-line)" />{[30,60,90,120,150,180].map(x => <path key={x} d={`M${x} 148v5`} stroke="var(--lab-muted)" />)}</svg>;
}
export function MicroscopePuzzle({ challenge: ch, ...props }) {
  const [proof, setProof] = useState({ sampleId: '', rotation: 0, offset: 0, focus: ch.stage === 0 ? 100 : 55, checkedWindows: [] });
  const [windowId, setWindow] = useState('A'), [overlay, setOverlay] = useState(false), [scores, setScores] = useState({});
  const selected = ch.samples.find(s => s.id === proof.sampleId), ref = ch.reference.ridges[windowId];
  const change = patch => { setProof({ ...proof, ...patch, checkedWindows: [] }); setScores({}); };
  const compare = () => { setScores({ ...scores, [windowId]: comparisonScore(ch, proof, windowId) }); setProof({ ...proof, checkedWindows: [...new Set([...proof.checkedWindows, windowId])] }); SoundFX.playCompare(); };
  const visual = <><div className="scene-label"><span>Сравнительный микроскоп</span><span>{ch.windows.length === 2 ? 'Два участка' : 'Один участок'}</span></div>{ch.windows.length === 2 && <div className="window-tabs">{ch.windows.map(w => <button key={w} type="button" aria-pressed={windowId === w} onClick={() => { setWindow(w); SoundFX.playNavigate(); }}>Участок {w}{proof.checkedWindows.includes(w) && <Check size={16} />}</button>)}</div>}<div className="microscope-pair"><div><span>Эталон</span><RidgeView ridges={ref} rotation={ch.reference.rotation} offset={ch.reference.offset} /></div><div><span>Образец инструмента</span>{selected ? <RidgeView ridges={selected.ridges[windowId]} rotation={proof.rotation} offset={proof.offset} focus={proof.focus} overlay={overlay} reference={{ ridges: ref, rotation: ch.reference.rotation, offset: ch.reference.offset }} /> : <div className="microscope-empty"><Microscope size={36} /><p>Выберите инструмент</p></div>}</div></div><div className="comparison-results" role="status">{ch.windows.map(w => <span key={w}>Участок {w}: {scores[w] === undefined ? 'не сравнивался' : `${scores[w]}%`}</span>)}</div><details className="instrument-data"><summary>Измерения для сравнения</summary><p>Эталон: борозды {ref.join(', ')}, наклон {ch.reference.rotation}°, смещение {ch.reference.offset}.</p>{selected && <p>Образец: борозды {selected.ridges[windowId].join(', ')}. Совместите положение и наклон.</p>}</details></>;
  const controls = <><Rule><strong>Критерий совпадения</strong><p>Не менее {ch.threshold}% на каждом участке. Процент учитывает расположение борозд, угол, смещение и чёткость — не только выбранное название инструмента.</p></Rule><div className="tool-options">{ch.samples.map(sample => <button key={sample.id} type="button" aria-pressed={proof.sampleId === sample.id} onClick={() => { change({ sampleId: sample.id }); SoundFX.playRotate(); }}><AlignHorizontalJustifyStart size={18} />{sample.label}</button>)}</div><RangeControl label="Совмещение угла" value={proof.rotation} min={-20} max={20} unit="°" onChange={rotation => change({ rotation })} />{ch.stage > 0 && <><RangeControl label="Смещение образца" value={proof.offset} min={-15} max={15} onChange={offset => change({ offset })} /><RangeControl label="Фокус" value={proof.focus} min={20} max={100} unit="%" onChange={focus => change({ focus })} /></>}<label className="overlay-switch"><input type="checkbox" checked={overlay} onChange={e => { setOverlay(e.target.checked); SoundFX.playClick(); }} />Наложить эталон</label><button type="button" className="lab-secondary" disabled={!selected} onClick={compare}><Microscope size={18} />Сравнить участок {windowId}</button></>;
  return <Frame {...props} proof={proof} visual={visual} controls={controls} instruction="Сопоставьте рисунок борозд, совместите образцы и выполните сравнение. Изменение настроек требует повторного сравнения." hint="Наложение помогает увидеть смещение. На последнем этапе подходящий инструмент должен совпасть на обоих участках. Для сравнения доступны и числовые измерения." />;
}

